server:
  port: 10001
spring:
  application:
    name: spring-boot-actuator
#  security:  # 配置spring Security
#    user:
#      name: actuator
#      password: actuator
#      roles: ACTUATOR_ADMIN
  boot:
    admin:
      client:
        url: http://localhost:8090
management:
  endpoints:
    web:
#      base-path: /minitor
      exposure:
        include: "*" ### 注意这里要有引号
#        exclude:
  endpoint:
    health:
      show-details: always # never  # when_authorized
    info:
      enabled: true
    shutdown:
      enabled: true # 实现优雅关闭spring boot服务
  health:
    mongo:
      enabled: false  #  配置mongo 组件关闭actuator健康监控
    defaults:
      enabled: true # 禁用所有自动配置的健康指示器
info:
  app:
    name: actuator-test-demo
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@  # 这个写法是如果是maven项目，引用maven里的变量
      target: @java.version@